apiVersion: v1
kind: Service
metadata:
  name: training-session-service
spec:
  type: LoadBalancer
  selector:
    app: trainingsessiondeployment
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
