apiVersion: v1
kind: Service
metadata:
  name: session-db-service
spec:
  type: LoadBalancer
  selector:
    app: session-db
  ports:
    - protocol: TCP
      port: 5433
      targetPort: 5432 
