apiVersion: apps/v1
kind: Deployment
metadata:
  name: workoutrecommendationdeployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: workoutrecommendationdeployment
  template:
    metadata:
      labels:
        app: workoutrecommendationdeployment
    spec:
      containers:
        - name: cloud-microserivces-main-workout-recommendation-service
          image: santhoshh27/cloud-microservices:workout-recommendation-service
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: workout-config
            - secretRef:
                name: groq-secret
          ports:
            - containerPort: 8000
