apiVersion: v1
kind: Service
metadata:
  name: workout-recommendation-service
spec:
  type: LoadBalancer
  selector:
    app: workoutrecommendationdeployment
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
