apiVersion: v1
kind: Service
metadata:
  name: user-management-service
spec:
  type: LoadBalancer
  selector:
    app: usermanagementdeployment
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
