apiVersion: v1
kind: Secret
metadata:
  name: db-secret
data:
  DB_HOST: c2Vzc2lvbi1kYi1zZXJ2aWNl
  DB_PORT: NTQzMg==
  DB_USER: dXNlcg==
  DB_PASSWORD: cGFzc3dvcmQ=
  DB_NAME: dXNlcnNlcnZpY2U=
  JWT_SECRET: eW91cl9qd3Rfc2VjcmV0X2tleV9oZXJl
  POSTGRES_PASSWORD: cGFzc3dvcmQ=


